
package webservices.Client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DDOClassService", targetNamespace = "http://Implementation.webservices/", wsdlLocation = "http://localhost:8888/DDOClass?wsdl")
public class DDOClassService
    extends Service
{

    private final static URL DDOCLASSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DDOCLASSSERVICE_EXCEPTION;
    private final static QName DDOCLASSSERVICE_QNAME = new QName("http://Implementation.webservices/", "DDOClassService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/DDOClass?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DDOCLASSSERVICE_WSDL_LOCATION = url;
        DDOCLASSSERVICE_EXCEPTION = e;
    }

    public DDOClassService() {
        super(__getWsdlLocation(), DDOCLASSSERVICE_QNAME);
    }

    public DDOClassService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DDOCLASSSERVICE_QNAME, features);
    }

    public DDOClassService(URL wsdlLocation) {
        super(wsdlLocation, DDOCLASSSERVICE_QNAME);
    }

    public DDOClassService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DDOCLASSSERVICE_QNAME, features);
    }

    public DDOClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DDOClassService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "DDOClassPort")
    public WebInterface getDDOClassPort() {
        return super.getPort(new QName("http://Implementation.webservices/", "DDOClassPort"), WebInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "DDOClassPort")
    public WebInterface getDDOClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Implementation.webservices/", "DDOClassPort"), WebInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DDOCLASSSERVICE_EXCEPTION!= null) {
            throw DDOCLASSSERVICE_EXCEPTION;
        }
        return DDOCLASSSERVICE_WSDL_LOCATION;
    }

}
