
package webservices.Client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LVLClassService", targetNamespace = "http://Implementation.webservices/", wsdlLocation = "http://localhost:8889/LVLClass?wsdl")
public class LVLClassService
    extends Service
{

    private final static URL LVLCLASSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LVLCLASSSERVICE_EXCEPTION;
    private final static QName LVLCLASSSERVICE_QNAME = new QName("http://Implementation.webservices/", "LVLClassService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8889/LVLClass?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LVLCLASSSERVICE_WSDL_LOCATION = url;
        LVLCLASSSERVICE_EXCEPTION = e;
    }

    public LVLClassService() {
        super(__getWsdlLocation(), LVLCLASSSERVICE_QNAME);
    }

    public LVLClassService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LVLCLASSSERVICE_QNAME, features);
    }

    public LVLClassService(URL wsdlLocation) {
        super(wsdlLocation, LVLCLASSSERVICE_QNAME);
    }

    public LVLClassService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LVLCLASSSERVICE_QNAME, features);
    }

    public LVLClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LVLClassService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "LVLClassPort")
    public WebInterface getLVLClassPort() {
        return super.getPort(new QName("http://Implementation.webservices/", "LVLClassPort"), WebInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "LVLClassPort")
    public WebInterface getLVLClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Implementation.webservices/", "LVLClassPort"), WebInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LVLCLASSSERVICE_EXCEPTION!= null) {
            throw LVLCLASSSERVICE_EXCEPTION;
        }
        return LVLCLASSSERVICE_WSDL_LOCATION;
    }

}
