
package webservices.Client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MTLClassService", targetNamespace = "http://Implementation.webservices/", wsdlLocation = "http://localhost:8887/MTLClass?wsdl")
public class MTLClassService
    extends Service
{

    private final static URL MTLCLASSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTLCLASSSERVICE_EXCEPTION;
    private final static QName MTLCLASSSERVICE_QNAME = new QName("http://Implementation.webservices/", "MTLClassService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8887/MTLClass?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTLCLASSSERVICE_WSDL_LOCATION = url;
        MTLCLASSSERVICE_EXCEPTION = e;
    }

    public MTLClassService() {
        super(__getWsdlLocation(), MTLCLASSSERVICE_QNAME);
    }

    public MTLClassService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTLCLASSSERVICE_QNAME, features);
    }

    public MTLClassService(URL wsdlLocation) {
        super(wsdlLocation, MTLCLASSSERVICE_QNAME);
    }

    public MTLClassService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTLCLASSSERVICE_QNAME, features);
    }

    public MTLClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTLClassService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "MTLClassPort")
    public WebInterface getMTLClassPort() {
        return super.getPort(new QName("http://Implementation.webservices/", "MTLClassPort"), WebInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "MTLClassPort")
    public WebInterface getMTLClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Implementation.webservices/", "MTLClassPort"), WebInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTLCLASSSERVICE_EXCEPTION!= null) {
            throw MTLCLASSSERVICE_EXCEPTION;
        }
        return MTLCLASSSERVICE_WSDL_LOCATION;
    }

}
