
package webservices.Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebInterface", targetNamespace = "http://webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebInterface {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTRecord", targetNamespace = "http://webservices/", className = "webservices.Client.CreateTRecord")
    @ResponseWrapper(localName = "createTRecordResponse", targetNamespace = "http://webservices/", className = "webservices.Client.CreateTRecordResponse")
    @Action(input = "http://webservices/WebInterface/createTRecordRequest", output = "http://webservices/WebInterface/createTRecordResponse")
    public String createTRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "displayRecord", targetNamespace = "http://webservices/", className = "webservices.Client.DisplayRecord")
    @ResponseWrapper(localName = "displayRecordResponse", targetNamespace = "http://webservices/", className = "webservices.Client.DisplayRecordResponse")
    @Action(input = "http://webservices/WebInterface/displayRecordRequest", output = "http://webservices/WebInterface/displayRecordResponse")
    public String displayRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferRecord", targetNamespace = "http://webservices/", className = "webservices.Client.TransferRecord")
    @ResponseWrapper(localName = "transferRecordResponse", targetNamespace = "http://webservices/", className = "webservices.Client.TransferRecordResponse")
    @Action(input = "http://webservices/WebInterface/transferRecordRequest", output = "http://webservices/WebInterface/transferRecordResponse")
    public String transferRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSRecord", targetNamespace = "http://webservices/", className = "webservices.Client.CreateSRecord")
    @ResponseWrapper(localName = "createSRecordResponse", targetNamespace = "http://webservices/", className = "webservices.Client.CreateSRecordResponse")
    @Action(input = "http://webservices/WebInterface/createSRecordRequest", output = "http://webservices/WebInterface/createSRecordResponse")
    public String createSRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editRecord", targetNamespace = "http://webservices/", className = "webservices.Client.EditRecord")
    @ResponseWrapper(localName = "editRecordResponse", targetNamespace = "http://webservices/", className = "webservices.Client.EditRecordResponse")
    @Action(input = "http://webservices/WebInterface/editRecordRequest", output = "http://webservices/WebInterface/editRecordResponse")
    public String editRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecordCounts", targetNamespace = "http://webservices/", className = "webservices.Client.GetRecordCounts")
    @ResponseWrapper(localName = "getRecordCountsResponse", targetNamespace = "http://webservices/", className = "webservices.Client.GetRecordCountsResponse")
    @Action(input = "http://webservices/WebInterface/getRecordCountsRequest", output = "http://webservices/WebInterface/getRecordCountsResponse")
    public String getRecordCounts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "displayAllRecords", targetNamespace = "http://webservices/", className = "webservices.Client.DisplayAllRecords")
    @ResponseWrapper(localName = "displayAllRecordsResponse", targetNamespace = "http://webservices/", className = "webservices.Client.DisplayAllRecordsResponse")
    @Action(input = "http://webservices/WebInterface/displayAllRecordsRequest", output = "http://webservices/WebInterface/displayAllRecordsResponse")
    public String displayAllRecords(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
